config/routes.rb
Rails.application.routes.draw do
  
  resources :meetings, except: [:destroy, :index]
  get 'meetings/index'

  resources :users
  
  resources :books
  resources :running_records
  resources :students, except: [:show]

   delete '/users/:id', to:'users#destroy', as: 'destroy_user'
   delete '/students/:id', to: 'students#destroy', as: 'destroy_student'
  
  get 'meetings/:id', to: 'meetings#index', as: 'show_meetings'
   delete '/meetings/:id', to: 'meetings#destroy', as: 'destroy_meeting'
  get '/users/:id/account', to: 'users#account', as: 'account'
  get '/users/:id', to: 'users#show', as: 'current_user'
  get '/students/:id', to: 'students#profile', as: 'profile'
  get '/sessions', to: 'sessions#create', as: 'session'
  post '/sessions/new', to: 'sessions#new', as: 'sessions'

 

  

  root 'welcome#index' #

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
belongs_to :user






extend SimpleCalendar
    belongs_to :calendar 
    has_many :dates


 #    def start_time
 #   self.Meeting.start_date.to_datetime
 # end

 # def end_time
 #   self.Meeting.end_date.to_datetime
 # end

   

 

    
# def start_time 
# 	self.User.start
# end

 # def end_time
 #   self.meeting.end_date
 # end


 # def start_time
 #        self.user.start ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
 #    end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = set_meeting
    
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to user_path(:current_user), notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
#   def destroy
#  @meeting.destroy
#     respond_to do |format|
#       format.html { redirect_to user_path(:current_user), notice: 'Meeting was successfully destroyed.' }
#       format.json { head :no_content }
    
    
#       #  # @meeting = Meeting.find(params[:id])
#       #  @meeting = Meeting.find(params[:id])
#       # if @meeting.destroy
#       # flash[:notice] = "This meeting was successfully deleted."
#       # redirect_to user_path(:current_user)
#       # else
#       #   flash[:alert] = "There was a problem deleting this meeting."
    
#  end
# end

def destroy 

  puts "PARAMS ARE " + params.inspect
       @meeting = Meeting.find(params[:id])
      if @meeting.destroy
      flash[:notice] = "This student was successfully deleted."
      redirect_to user_path(current_user)
      else
        flash[:alert] = "There was a problem deleting this student."
        redirect_to user_path(@user)
  # puts "PARAMS ARE " + params.inspect
  #   @meeting = meeting_id
  #   @meeting.destroy 
  #   respond_to do |format|
  #     format.html { redirect_to user_path(current_user), notice: 'Meeting was successfully destroyed.' }
  #     format.json { head :no_content }
    
  #   flash[:notice] = "This meeting was successfully deleted."
  end
end


  private
    # Use callbacks to share common setup or constraints between actions.
     def current_user
      @user = User.find(params[:id])
    end

    def set_meeting
      @meeting = Meeting.find_by(id: params[:id])
      end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time)
    end
  end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= simple_form_for(@meeting) do |f| %>
  <%= f.error_notification %>

    <%= f.input :name %>

    <div class="row">
    <div class="col-sm-6" style="background-color:yellow;">

	<%= f.input :start_time %>
</div>
<div class="col-sm-6" style="background-color:pink;">

    <%= f.input :end_time %>
   </div>
  </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Today's Events/Lessons</h1>

<div class="meetings">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>



     <% @meetings = Meeting.all %>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.start_time.strftime('%H:%M') %></td>
        <td><%= meeting.end_time.strftime('%H:%M') %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</div>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>
</div>
<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>