config/routes.rb
Rails.application.routes.draw do
  
  resources :meetings, except: [:destroy, :index]
  get 'meetings/index'

  resources :users
  
  resources :books
  resources :running_records
  resources :students, except: [:show]

   delete '/users/:id', to:'users#destroy', as: 'destroy_user'
   delete '/students/:id', to: 'students#destroy', as: 'destroy_student'
  
  get 'meetings/:id', to: 'meetings#index', as: 'show_meetings'
   delete '/meetings/:id', to: 'meetings#destroy', as: 'destroy_meeting'
  get '/users/:id/account', to: 'users#account', as: 'account'
  get '/users/:id', to: 'users#show', as: 'current_user'
  get '/students/:id', to: 'students#profile', as: 'profile'
  get '/sessions', to: 'sessions#create', as: 'session'
  post '/sessions/new', to: 'sessions#new', as: 'sessions'

 

  

  root 'welcome#index' #

end

app/models/student.rb
class Student < ActiveRecord::Base
belongs_to :user 
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @student = Student.all
  end

     def create
  @student = Student.new(student_params)
    if @student.save 
      flash[:notice] = "You have successfully created a new student."
      redirect_to students_path
    else
      flash[:alert] = "There was a problem creating a student.  Please try again"
      redirect_to new_student_path
  
  end
  end

  def new
    @student = Student.new
    @session = Session.new
  end

  def edit
  end

  def show
      @student = Student.find_by_id(params[:id])
  end


  def profile
      @student = Student.find_by_id(params[:id])
end


  def update
  end

def destroy
         puts "PARAMS ARE " + params.inspect
       @student = Student.find(params[:id])
      if @student.destroy
      flash[:notice] = "This student was successfully deleted."
      redirect_to root_path
      else
        flash[:alert] = "There was a problem deleting this student."
        redirect_to user_path(@user)
    end
end
     
#      if Student.destroy(@student)
#       flash[:notice] = "This student was successfully deleted."
#       redirect_to students_path
#       else 
#         flash[:alert] = "There was a problem deleting this student"
#         redirect_to students_path

# end
# end  

private

def student_params
    params.require(:student).permit(:fname, :lname, :current_lexile_level, :current_guided_reading_level)
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<!DOCTYPE html>
<html>
<head>
</head>

<body>

 <div class="panel panel-default">
 
  <div class="panel-body2">
    
 
  <%= link_to "Home", root_path, class: "circle" %>

  
  </div>    
</div>

<div class="margin">
<table class="table table-hover">

		<tr class="active">
  		   <td><%= "Student's Name"  %></td>

         <td><%= "Classroom Number" %></td>
  			
  		   <td><%= "Current Lexile Level" %></td>

  		   <td><%=  "Current Guided Reading Level" %></td>
         <td><%= " " %></td>
  		</tr>


		<% @student.each do |student| %>
		<tr class="active">
	
  		   
         <td><%= link_to "#{student.fname + " " + student.lname}", profile_path(student.id), class: "name" %></td>
  	     
         <td><%= student.id %></td>
  			
  		   <td><%= student.current_lexile_level %></td>

  		   <td><%= student.current_guided_reading_level %></td>

         <td><%= link_to 'Delete This Student', destroy_student_path(student.id), method: :delete %></td>
  		</tr>
  		<% end %> 
</div>  

  	


</table>


</body>

</html>

app/views/students/new.html.erb
   
<%= link_to 'Log Out', root_path, class: "rectangle3" %>
<div class="panel panel-default">
  <div class="panel-body">
 


<!-- Button trigger modal -->
<button type="button" class="circle" data-toggle="modal" data-target="#myModal">
  Add a Student
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Student</h4>
      </div>
      <div class="modal-body">
        <div class="sign_up">
      <%= simple_form_for @student do |f| %>
      
       <%= f.input :fname %>
       <%= f.input :lname %>
         <%= f.input :current_lexile_level  %>
         <%= f.input :current_guided_reading_level %>
         
         <%= f.button :submit, class: "circle" %>
    <% end %>
    </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>



<!-- Button trigger modal -->
<button type="button" class="circle" data-toggle="modal" data-target="#myModal">
  Add a Running Record
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Student</h4>
      </div>
      <div class="modal-body">
        <div class="sign_up">
      <%= simple_form_for Student.new do |f| %>
      
       <%= f.input :fname %>
       <%= f.input :lname %>
         <%= f.input :current_lexile_level  %>
         <%= f.input :current_guided_reading_level %>
         
         <%= f.button :submit, class: "circle" %>
    <% end %>
    </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

 </div>
 <div class="panel-footer"></div></span>
</div>


</body>
</html>

app/views/students/profile.html.erb
 	 
<%= link_to 'Log Out', root_path, class: "rectangle3" %>
<div class="title">
<%= "Student Learning Profile for " + @student.fname + " " + @student.lname %>
</div>

	<tr class="active">
			<td><%= @student.id %></td>
  			
  		   <td><%= @student.current_lexile_level %></td>

  		   <td><%= @student.current_guided_reading_level %></td>

  		   <%= link_to 'Delete This Student', destroy_student_path, method: :delete, class: "circle" %>
 	

 	 </tr>

app/views/students/show.html.erb
<!DOCTYPE html>
<html>
<head>
</head>

<body>


<%= "Hello! #{student.fname}" %>


  