config/routes.rb
Rails.application.routes.draw do
  
  resources :meetings, except: [:destroy, :index]
  get 'meetings/index'

  resources :users
  
  resources :books
  resources :running_records
  resources :students, except: [:show]

   delete '/users/:id', to:'users#destroy', as: 'destroy_user'
   delete '/students/:id', to: 'students#destroy', as: 'destroy_student'
  
  get 'meetings/:id', to: 'meetings#index', as: 'show_meetings'
   delete '/meetings/:id', to: 'meetings#destroy', as: 'destroy_meeting'
  get '/users/:id/account', to: 'users#account', as: 'account'
  get '/users/:id', to: 'users#show', as: 'current_user'
  get '/students/:id', to: 'students#profile', as: 'profile'
  get '/sessions', to: 'sessions#create', as: 'session'
  post '/sessions/new', to: 'sessions#new', as: 'sessions'

 

  

  root 'welcome#index' #

end

app/models/user.rb
class User < ActiveRecord::Base
has_many :students
has_many :books
has_many :meetings
has_one :session
# accepts_nested_attributes_for :session, allow_destroy: true
belongs_to :session
# validates :fname, presence: true
# validates :lname, presence: true
# validates :username, presence: true


extend SimpleCalendar
    belongs_to :user
    has_many :meetings


   
# accepts_nested_attributes_for :session, allow_destroy: true

# accepts_nested_attributes_for :students, :reject_if => :all_blank, :allow_destroy => true
 #has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  #validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
layout 'users'

  def index
    @users = User.all
    if @users.present?
      flash[:notice] = "Here is a list of all Users."
    else
      flash[:alert] = "Sorry, there were no users to display."
  end
end

  def create
  @user = User.create(user_params)

if
   @user = User.new(user_params)
   @user.save!

      flash[:notice] = "Your account was created successfully.  You have been logged in."
    
       redirect_to user_path(@user)
      # flash[:alert] = "There was a problem creating your account."
    else 
    
      flash[:alert] = "Please enter the required information in the fields."
end
  end


  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:notice] = "Your account was successfully updated."
      redirect_to user_path(@user)
      else
      flash[:alert] = "There was a problem updating your account."
        render 'edit'
  end
end

  def show
    @user = User.find_by(params[:current_user])
   
   

end

  def account
  @user = current_user

end

  def destroy
       puts "PARAMS ARE " + params.inspect
       @user = User.find(params[:id])
      if @user.destroy
      flash[:notice] = "Your account was successfully deleted."
      redirect_to root_path
      else
        flash[:alert] = "There was a problem deleting your account."
        redirect_to user_path(@user)
      end
    end
 

     private


  # def current_user
  #   @user = User.find(params[:id])
  # end



  def user_params
   params.require(:user).permit(:fname, :lname, :username, :email, :password, :parent, :students_first_name, :students_last_name, :teacher_name)
     end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_book.html.erb
<!-- Button trigger modal -->
<button type="button" class="rectangle5" data-toggle="modal" data-target="#myModal3">
  Add a Book
</button>

<!-- Modal -->
<div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add A Book</h4>
      </div>
      <div class="modal-body">
        
        <div class="sign_up">
          <%= simple_form_for Book.new, :url => url_for(:controller => 'books', :action => 'create')do |f| %> 
           <%= f.input :title %>
           <%= f.input :author %>
           <%= f.input :lexile_level  %>
           <%= f.input :guided_reading_level %>   
           <%= f.button :submit, class: "circle" %>
           <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/users/_event.html.erb
<div id="meetings_grid" >
  <% @meetings = Meeting.all %>
  <% @meetings.each do |meeting| %>
  <%= link_to meeting.name, meetings_path, remote: true %>
  <% end %>
</div>

app/views/users/_meeting.html.erb
<div class="lighter">
  <% n = 1  %>
  <% $num = 31 %>
  <% while n < 31 do %> 
    <%= month_calendar do |date, meeting| %>
      <%= date.day %>
      <%= n %>
      <%= render partial: 'event', locals: { meetings: @meetings} %>
        <%= simple_form_for Meeting.new, :url => url_for(:controller => 'meetings', :action => 'create', :method => 'post'), remote: true do |f| %> 
            <div class="name">
              <%= f.label "Event Name:" %>
              <%= f.input :name, :label => false   %>
            </div>
            <div class="label1">
              <%= f.label "Start Time:" %>
            </div>
            <div class="start">
              <%= f.time_select :start_time, {:ampm => true} %> 
            </div>     
            <div class="label2">
              <%= f.label "End Time:" %>
            </div>
            <div class="end">
              <%= f.time_select :end_time, {ampm: true}  %>
            </div>  
              <%= f.button :submit, id: "#{n}" %>
                <div class="empty">
                </div>
              <% n += 1 %>
              <% end %>
        <% end %>
     <% end %>
</div>   

app/views/users/_student.html.erb
       
<!-- Button trigger modal -->
      <button type="button" class="rectangle4" data-toggle="modal" data-target="#myModal">
        Add a Student
      </button>
      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">New Student</h4>
            </div>
            <div class="modal-body">
              <div class="sign_up">
                <%= simple_form_for Student.new, :url => url_for(:action => 'create', :controller => 'students'),
                  :method => 'post' do |f| %>
                    <%= f.input :fname %>
                    <%= f.input :lname %>
                    <%= f.input :current_lexile_level  %>
                    <%= f.input :current_guided_reading_level %>
                    <%= f.button :submit, class: "circle" %>
                  <% end %>
              </div>
              <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
      </div>

app/views/users/account.html.erb
 <div class="panel panel-default">

<%= link_to 'Delete Your Account', destroy_user_path, method: :delete, class: "circle" %>

<!-- Button trigger modal -->
<button type="button" class="circle" data-toggle="modal" data-target="#myModal2">
 Edit Your Account  
</button>

<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Your Account</h4>
      </div>
      <div class="modal-body">
      <div class="sign_up">
       <%= simple_form_for User.find(params[:id]), :url => url_for(:action => 'update', :controller => 'users'),
    :method => 'patch' do |f|  %>
			
		 	 <%= f.input :username, placeholder: '12 characters', :required => true, label_html: { class: 'my_class' } %>
			 <%= f.input :password, placeholder: '8 characters', hint: false, :required => true, error_html: { id: 'password_error'} %>
		  	 <%= f.input :email, placeholder: 'user@domain.com', :required => true %>
        
  
		  	
		  	 <%= f.button :submit, class: "circle" %>
			<% end %>
		</div>

      <div class="modal-footer">
       <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> 
        
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/application.js.erb
// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
// or any plugin's vendor/assets/javascripts directory can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file.
//
// Read Sprockets README (https://github.com/rails/sprockets#sprockets-directives) for details
// about supported directives.
//
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap-sprockets
//= require cocoon
//= require_tree .


$(document).ready(function() {
	$(".rectangle").hover(function() {
		$(".rectangle").css("background-color", "white")
	})
})

$(document).ready(function() {
	$(".rectangle").mouseleave(function() {
		$(".rectangle").css("background-color", "#FF6600")
	})
})


$(document).ready(function() {
	$(".rectangle2").hover(function() {
		$(".rectangle2").css("background-color", "white")
	})
})

$(document).ready(function() {
	$(".rectangle2").mouseleave(function() {
		$(".rectangle2").css("background-color", "deeppink")
	})
})


$(document).ready(function() {
	$(".rectangle3").hover(function() {
		$(".rectangle3").css("background-color", "white")
	})
})

$(document).ready(function() {
	$(".rectangle3").mouseleave(function() {
		$(".rectangle3").css("background-color", "red")
	})
})


$(document).ready(function() {
	$(".rectangle4").hover(function() {
		$(".rectangle4").css("background-color", "white")
	})
})

$(document).ready(function() {
	$(".rectangle4").mouseleave(function() {
		$(".rectangle4").css("background-color", "#00E600")
	})
})


$(document).ready(function() {
	$(".rectangle5").hover(function() {
		$(".rectangle5").css("background-color", "white")
	})
})

$(document).ready(function() {
	$(".rectangle5").mouseleave(function() {
		$(".rectangle5").css("background-color", "#FFFF00")
	})
})

 // $(document).ready(function() {
 //            $("#but").click(function() {
 //                var n = $(this).attr("n");
 //                alert(n);
 //            });
 //        });


function submitForm() {
   for (n = 1; n < 35; n++) {
   var num = new Array(n)
   }
  for (i = 0; i < num.length; i++) { 
  
  
  $(document).ajaxSuccess(function( event, request, settings) {
    $(".btn").click(function() {
      	$( "#display" ).load( "users/test.html.erb" );
      	// $(this).siblings("div.empty").text( "Triggered ajaxComplete handler." )  )  
})
})

 


   	// 	$(document).ready(function() {
   	// 		$(num[i]).click(function() {
				// $(".simple-calendar").text("hello there")
   	// 	})
   	// 		})
   	}
   }


submitForm()


// $(document).ready(function() {
// 	$(".rectangle").submit(function () {
// 	 		$("Meeting.new.id").css("background-color", "purple")
// 	})
// })




// $(document).ready(function() {
//     $("#submit").submit(function() { 
//         // var val = $("input[type=submit][clicked=true]").val();
//         $("#submit").css("background-color", "purple")
//         $("#submit").css("padding", "100px")
//         $("#submit").animate("margin-left": "100px")
//         // DO WORK
//     });
// });

app/views/users/destroy.html.erb
<h1>Your 

app/views/users/index.html.erb
<div class="panel panel-default">
 
  <div class="panel-body2">





</div>
</div>


<div class="users">
<ul><% @users.each do |user| %>
<li><%= user.fname  %> 
	<%= user.id %>
<%= user.lname %>
<%= user.email %></li>

<% end %>

</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      User Profile
    </title>
  </head>
  <body>
      <div class="panel panel-default">   
        <div class="panel-body">
          
          <%= render 'student' %>
          <%= render 'book' %>
          <%= link_to 'Your Account', account_path(@user), class: "rectangle2" %>
          <%= link_to 'Log Out', root_path, class: "rectangle3" %>
        </div>
      
        
          <%= render partial: 'meeting', locals: { meetings: @meetings} %>
        </div>
 </div>
</div>

     
      
     
      









 
     




 
    </div>



 



 

    


        
 <% @meeting = Meeting.all %>
 <div class ="schedule">
  Today's Schedule
</div>
    <% @meeting.each do |meeting| %>

      <tr>
   
       
          

      <%= link_to meeting.name + "#{meeting.start_time.strftime("%I:%M%p")}" + "-" + "#{meeting.end_time.strftime("%I:%M%p")}" + " " %> <br> 
       <%= link_to 'Edit', edit_meeting_path(meeting) %> 
       <%= link_to 'Delete', destroy_meeting_path(meeting), method: :delete, data: { confirm: 'Are you sure?' } %>
     
      </tr>
       
      

       
   


       
       <% end %>

   


       

 










</div>








   

 
</div>




</body>

</html>

app/views/users/test.html.erb
<div id="display">
	Here is some content
</div>