config/routes.rb
Rails.application.routes.draw do
  
  resources :meetings, except: [:destroy, :index]
  get 'meetings/index'

  resources :users
  
  resources :books
  resources :running_records
  resources :students, except: [:show]

   delete '/users/:id', to:'users#destroy', as: 'destroy_user'
   delete '/students/:id', to: 'students#destroy', as: 'destroy_student'
  
  get 'meetings/:id', to: 'meetings#index', as: 'show_meetings'
   delete '/meetings/:id', to: 'meetings#destroy', as: 'destroy_meeting'
  get '/users/:id/account', to: 'users#account', as: 'account'
  get '/users/:id', to: 'users#show', as: 'current_user'
  get '/students/:id', to: 'students#profile', as: 'profile'
  get '/sessions', to: 'sessions#create', as: 'session'
  post '/sessions/new', to: 'sessions#new', as: 'sessions'

 

  

  root 'welcome#index' #

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'

  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_login.html.erb
<button type="button" class="circle" data-toggle="modal" data-target="#myModal">
 Log In
</button>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Log In</h4>
      </div>
      <div class="modal-body">
      <div class="login">

        <%= simple_form_for sessions_path, method: :get do |f| %>
      
       <%= f.input :username %>
       <%= f.input :password %>
         <%= f.input :email  %>
  
         
         <%= f.button :submit, "Log In", class: "circle" %>

       
         <% end %>
        </div>
     
    
   

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       
      </div>
    </div>
  </div>
</div>
</div>

app/views/welcome/_registration.html.erb
<div class="registration">
<!-- Button trigger modal -->
<button type="button" class="circle" data-toggle="modal" data-target="#myModal">
  Sign Up
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign up!</h4>
      </div>
      <div class="modal-body">
        <div class="sign_up">
 
		<div class="sign_up">

		
  			<%= simple_form_for User.new, :url => url_for(:controller => 'users', :action => 'create') do |f| %>
  			 <%= f.input :fname, :required => true %>
			 <%= f.input :lname, :required => true %>
		 	 <%= f.input :username, placeholder: '12 characters', :required => true %>
			 <%= f.input :password, :required => true %>
		  	 <%= f.input :email, placeholder: 'user@domain.com', :required => true %>
		  	 <%= f.input :parent, :required => false %>
		  	 <%= f.input :students_first_name, :required => false, hint: 'Only answer if you are a parent' %>
		  	 <%= f.input :students_last_name, :required => false, hint: 'Only answer if you are a parent' %>
		  	 <%= f.input :teacher_name, :required => false, hint: 'Only answer if you are a parent' %>
		  	 <%= f.input :avatar, :required => false, :as => :file %>

		  	 <%= f.button :submit, class: "circle" %>
			<% end %>
		
		</div>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Sign-up!</title>
	</head>

	<body>
		<div class="buttons">
		
			<%=	render :partial => 'registration', :object => {:user => @user} %>	
			
			<%=	render :partial => 'login', :object => {:session => @session} %>	
			
		</div>
		<header>	
			<h1>Bookworm</h1>
		</header>	
			<div class="background">
				<div class="main">
					<div class="main2">
					<br>
					<div class="paragraph">Welcome to my teaching app!  This app is designed to help teachers keep track of their students' information and progress.  This app will include many features, including:</div>
						<ul>
							<li>A feature that allows teachers to scan books and get information about that book's title, author, Fountas and Pinnell level, and Lexile level.</li>
							<li>A feature that allows teachers to upload and read ebooks</li>
							<li>A feature that allows teachers to record their students while they are reading these ebooks.</li>
							<li>A feature that allows teachers to keep track of their students' reading lists</li>
						</ul>
					</div>
					<div class="main3">
						<ul>
							<li>A feature that allows teachers to keep track of past running records, all their students reading lists, notes on their students' progress</li>
						</ul>
					<div class="paragraph">All of these features are designed with the intention of allowing teachers to keep track of and to organize their students' progress</div>
					</div>
				</div>
			<div>
		</div>


	<div class="footer">
		<footer>
		</footer>
	</div>